### ISSUE TITLE
Time computation is incorrect

### ISSUE THREAD

**Issue by mgedmin** [mgedmin/memgraphinator#6]
I had a script running for just under two hours, and when zoomed out, memgraphinator claimed I was looking at data points more than 3 hours in the past.

**Comment by Zren** [comment]
```
def format_time_ago(seconds):
    if seconds < 60:
        return '%d seconds ago' % seconds
    elif seconds < 60 * 60:
        m, s = divmod(seconds, 60)
        return '%d minutes, %d seconds ago' % (m, s)
    else:
        m, s = divmod(seconds, 60)
        h, m = divmod(m, 24)
        return '%d hours, %d minutes, %d seconds ago' % (h, m, s)
```

Looks like you accidentally divided `m` (minutes) by 24 instead of 60 minutes to calculate hours (and the remaining minutes).

**Comment by mgedmin** [comment]
OMG thank you for noticing!

:sparkles: what is math :sparkles:
