### ISSUE TITLE
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

### ISSUE THREAD

**Issue by mgedmin** [mgedmin/memgraphinator#8]
memgraphinator does not work on Ubuntu 19.04.

More specifically, it works, but it cannot draw the graph itself.  All I see is a white box and a bunch of these errors on the console:

```
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
```

**Comment by mgedmin** [comment]
Google tells me I'm missing `python-gi-cairo`.

I do have `python3-gi-cairo` installed, and running memgraphinator under Python 3 works fine.

**Comment by luisliborio** [comment]
is it solved? How? Same issue here.

**Comment by mgedmin** [comment]
@mughuara do you have the gobject introspection bindings for Cairo installed in your system?  On Ubuntu that's the python3-gi-cairo package.  I'm less familiar with other distros.

**Comment by luisliborio** [comment]
> @mughuara do you have the gobject introspection bindings for Cairo installed in your system? On Ubuntu that's the python3-gi-cairo package. I'm less familiar with other distros.

Thanks! That's exactly what I needed.
